name: Flutter CI

on:
  push:
    branches: [ master, release/* ]
  pull_request:
    branches: [ master, release/* ]
    
jobs:
  build:
    runs-on: macui-Mac
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
