name: Flutter CI

on:
  push:
    branches: [ master, release/* ]
  pull_request:
    branches: [ master, release/* ]
    
jobs:
  build:
    runs-on: macui-Mac
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pub Get Packages
        run: flutter pub get
        
      - name: build appbundle
        run: flutter build appbundle
        
      - name: build iOS
        run: flutter build ios
